export const COLOR_NAME_MAP: Record<string, { zh: string; en: string }> = {
  '红色': { zh: '红色', en: 'Red' },
  '蓝色': { zh: '蓝色', en: 'Blue' },
  '绿色': { zh: '绿色', en: 'Green' },
  '黄色': { zh: '黄色', en: 'Yellow' },
  '黑色': { zh: '黑色', en: 'Black' },
  '白色': { zh: '白色', en: 'White' },
  '灰色': { zh: '灰色', en: 'Gray' },
  '粉色': { zh: '粉色', en: 'Pink' },
  '紫色': { zh: '紫色', en: 'Purple' },
  '橙色': { zh: '橙色', en: 'Orange' },
  '棕色': { zh: '棕色', en: 'Brown' },
  '米色': { zh: '米色', en: 'Beige' },
  '银色': { zh: '银色', en: 'Silver' },
  '金色': { zh: '金色', en: 'Gold' },
  '青色': { zh: '青色', en: 'Cyan' },
  '卡其色': { zh: '卡其色', en: 'Khaki' },
  '藏青色': { zh: '藏青色', en: 'Navy' },
  '酒红色': { zh: '酒红色', en: 'Burgundy' },
  '深蓝色': { zh: '深蓝色', en: 'Dark Blue' },
  '浅蓝色': { zh: '浅蓝色', en: 'Light Blue' },
  '深绿色': { zh: '深绿色', en: 'Dark Green' },
  '浅绿色': { zh: '浅绿色', en: 'Light Green' },
  '深灰色': { zh: '深灰色', en: 'Dark Gray' },
  '浅灰色': { zh: '浅灰色', en: 'Light Gray' },
  '深红色': { zh: '深红色', en: 'Dark Red' },
  '浅红色': { zh: '浅红色', en: 'Light Red' },
  '深紫色': { zh: '深紫色', en: 'Dark Purple' },
  '浅紫色': { zh: '浅紫色', en: 'Light Purple' },
  '深黄色': { zh: '深黄色', en: 'Dark Yellow' },
  '浅黄色': { zh: '浅黄色', en: 'Light Yellow' },
  '深棕色': { zh: '深棕色', en: 'Dark Brown' },
  '浅棕色': { zh: '浅棕色', en: 'Light Brown' },
  '深橙色': { zh: '深橙色', en: 'Dark Orange' },
  '浅橙色': { zh: '浅橙色', en: 'Light Orange' },
  '深粉色': { zh: '深粉色', en: 'Dark Pink' },
  '浅粉色': { zh: '浅粉色', en: 'Light Pink' },
  '深青色': { zh: '深青色', en: 'Dark Cyan' },
  '浅青色': { zh: '浅青色', en: 'Light Cyan' },
  '深卡其色': { zh: '深卡其色', en: 'Dark Khaki' },
  '浅卡其色': { zh: '浅卡其色', en: 'Light Khaki' },
  '深藏青色': { zh: '深藏青色', en: 'Dark Navy' },
  '浅藏青色': { zh: '浅藏青色', en: 'Light Navy' },
  '深酒红色': { zh: '深酒红色', en: 'Dark Burgundy' },
  '浅酒红色': { zh: '浅酒红色', en: 'Light Burgundy' },
  '深银色': { zh: '深银色', en: 'Dark Silver' },
  '浅银色': { zh: '浅银色', en: 'Light Silver' },
  '深金色': { zh: '深金色', en: 'Dark Gold' },
  '浅金色': { zh: '浅金色', en: 'Light Gold' },
  '深米色': { zh: '深米色', en: 'Dark Beige' },
  '浅米色': { zh: '浅米色', en: 'Light Beige' },
  '深白色': { zh: '深白色', en: 'Off White' },
  '浅白色': { zh: '浅白色', en: 'Pure White' },
  '深黑色': { zh: '深黑色', en: 'Jet Black' },
  '浅黑色': { zh: '浅黑色', en: 'Charcoal' },
}

export function getLocalizedColorName(name: string, locale: string): string {
  const normalized = name.trim()
  const colorEntry = COLOR_NAME_MAP[normalized]
  if (colorEntry) {
    return locale === 'zh' ? colorEntry.zh : colorEntry.en
  }
  return normalized
}
